apiVersion: v1
kind: Pod
metadata:
  name: redis-node2
  labels:
    name: redis
    node: node2
spec:
  containers:
  -
    name: redis
    image: relaxart/kubernetes-redis-cluster:latest
    ports:
    - containerPort: 6379
    volumeMounts:
    - mountPath: /data
      name: redis-data
    env:
      - name: MASTER_ADDRESS
        value: "redis-node1-service"
      - name: ANNOUNCE_IP
        value: "redis-node2-service"
  volumes:
    - name: redis-data
      emptyDir: {}